DROP TABLE IF EXISTS admin_audit_log CASCADE;
DROP TABLE IF EXISTS property_reports CASCADE;
DROP TABLE IF EXISTS units CASCADE;
DROP TABLE IF EXISTS properties CASCADE;
DROP TABLE IF EXISTS tenant_profiles CASCADE;
DROP TABLE IF EXISTS landlord_profiles CASCADE;
DROP TABLE IF EXISTS users CASCADE;